server:
  port: 8070

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres:5432/order
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.ecommerce.order.dto.OrderConfirmation


application:
  config:
    customer-url: http://gateway-service:8222/api/v1/customers
    product-url: http://gateway-service:8222/api/v1/products
    payment-url: http://gateway-service:8222/api/v1/payments

