server:
  port: 8060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerialzer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.ecommerce.payment.dto.PaymentNotification

